### ISSUE TITLE
无法将类 AsyncTask<Params,Progress,Result>中的方法 execute应用到给定类型

### ISSUE THREAD

**Issue by ZhuLeon** [litesuits/android-lite-async#2]
我是把library导入到Android Studio里，报了这个异常：

Error:(76, 21) 错误: 无法将类 AsyncTask<Params,Progress,Result>中的方法 execute应用到给定类型;
需要: CAP#1[]
找到: 没有参数
原因: 形式 varargs 元素类型CAP#1无法从 类 <匿名com.litesuits.android.async.TaskExecutor$1> 进行访问
其中, Params,Progress,Result是类型变量:
Params扩展已在类 AsyncTask中声明的Object
Progress扩展已在类 AsyncTask中声明的Object
Result扩展已在类 AsyncTask中声明的Object
其中, CAP#1是新类型变量:
CAP#1从?的捕获扩展Object

**Comment by ByteRax** [comment]
把所有的?改为Object就OK了

**Comment by luckyjmcc** [comment]
一点也不ok

**Comment by litesuits** [comment]
使用1.7或者1.6版本的java编译
